name: integration_tests
on: [push]

jobs:
  integration_tests:
    runs-on: ubuntu-20.04  # linux required if you want to use docker
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Ignition
        run: |
          apt-get update
          apt-get install -y git python3
          git clone --depth 1 https://github.com/osrf/gzdev /tmp/gzdev
          pip3 install -r /tmp/gzdev/requirements.txt
          /tmp/gzdev/gzdev.py \
            repository repository enable osrf stable
          apt-get update
          apt-get install -y ignition-fortress
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: mbzirc
          target-ros2-distro: galactic
      - name: Compile and run tests
        run: docker build -t mbzirc_sim . -f docker/tests/Dockerfile
